import {
  Award,
  Briefcase,
  Calendar,
  DollarSign,
  FileText,
  Ghost,
  Linkedin,
  Mail,
  Phone,
  Users,
  X,
} from "lucide-react";
import { Stage } from "../types/stages";

export const availableStages: Stage[] = [
  {
    id: "jobpost",
    name: "Job Post",
    icon: Briefcase,
    position: null,
    application_id: null,
    auth_user: null,
  },
  {
    id: "mailsent",
    name: "Mail Sent",
    icon: Mail,
    position: null,
    application_id: null,
    auth_user: null,
  },
  {
    id: "callmade",
    name: "Call Made",
    icon: Phone,
    position: null,
    auth_user: null,
    application_id: null,
  },
  {
    id: "meeting",
    name: "Meeting",
    icon: Users,
    position: null,
    application_id: null,
    auth_user: null,
  },
  {
    id: "techtest",
    name: "Technical Test",
    icon: FileText,
    position: null,
    application_id: null,
    auth_user: null,
  },
  {
    id: "interview",
    name: "Interview",
    icon: Calendar,
    position: null,
    application_id: null,
    auth_user: null,
  },
  {
    id: "offer",
    name: "Offer",
    icon: DollarSign,
    position: null,
    application_id: null,
    auth_user: null,
  },
  {
    id: "acceptance",
    name: "Acceptance",
    icon: Award,
    position: null,
    application_id: null,
    auth_user: null,
    category: "Closer",
  },
  {
    id: "rejection",
    name: "Rejection",
    icon: X,
    position: null,
    application_id: null,
    auth_user: null,
    category: "Closer",
  },
  {
    id: "linkedin-easyapply",
    name: "Easy Apply",
    icon: Linkedin,
    position: null,
    application_id: null,
    auth_user: null,
  },
  {
    id: "ghosted",
    name: "Ghosted",
    icon: Ghost,
    position: null,
    application_id: null,
    auth_user: null,
    category: "Closer",
  },
];
